host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: "rhel:8"
    operating_system:
      name: rhel
      version: "8.0"
    python_version: "3.8"
    recommendation_type: latest
    limit_latest_versions: 5

managers:
  - name: update
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      maintainers:
        - goern
        - fridex
        - harshad16
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
