#!/usr/bin/env python3
# sesheta-actions
# Copyright(C) 2019 Christoph Görn
#
# This program is free software: you can redistribute it and / or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

"""Sesheta actions: merge master into pull request."""


import os

import click
import logging

from thoth.common import init_logging
from aicoe.sesheta.actions import __version__
from aicoe.sesheta.actions.pull_request import merge_master_into_pullrequest


init_logging()

_LOGGER = logging.getLogger("merge_master_into_pullrequest")
_LOGGER.info(f"Sesheta action: merge_master_into_pullrequest, Version v{__version__}")

SESHETA_ACTION_GITHUB_ACCESS_TOKEN = os.getenv("SESHETA_ACTION_GITHUB_ACCESS_TOKEN", None)


@click.command()
@click.option(
    "-v", "--verbose", is_flag=True, envvar="SESHETA_ACTION_VERBOSE", help="Be verbose about what's going on."
)
@click.option(
    "-t",
    "--github-access-token",
    envvar="SESHETA_ACTION_GITHUB_ACCESS_TOKEN",
    help="A token to authenticate with GitHub.",
)
@click.argument("owner")
@click.argument("repo")
@click.argument("pull_request")
def cli(owner: str, repo: str, pull_request: int, verbose: bool = False, github_access_token: str = None):
    """Command line interface for Sesheta action."""

    if verbose:
        _LOGGER.setLevel(logging.DEBUG)
        _LOGGER.debug("Debug mode turned on")

    _LOGGER.debug(f"Token: {github_access_token}")

    merge_master_into_pullrequest(owner, repo, pull_request, token=github_access_token)


if __name__ == "__main__":
    cli()
